# -*- coding: utf-8 -*-
"""micrograd_exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPTx1RXtBfc4MaTkf7viZZD4U2F9gtKN

# micrograd exercises

1. watch the [micrograd video](https://www.youtube.com/watch?v=VMj-3S1tku0) on YouTube
2. come back and complete these exercises to level up :)

## section 1: derivatives
"""

# here is a mathematical expression that takes 3 inputs and produces one output
from math import sin, cos

def f(a, b, c):
  return -a**3 + sin(3*b) - 1.0/c + b**2.5 - a**0.5

print(f(2, 3, 4))

# write the function df that returns the analytical gradient of f
# i.e. use your skills from calculus to take the derivative, then implement the formula
# if you do not calculus then feel free to ask wolframalpha, e.g.:
# https://www.wolframalpha.com/input?i=d%2Fda%28sin%283*a%29%29%29

def gradf(a, b, c):
  return [(-3*a**2)-(0.5/a**0.5), cos(3*b)*3+(5/2*b**1.5), 1/c**2] # todo, return [df/da, df/db, df/dc]

# expected answer is the list of
ans = [-12.353553390593273, 10.25699027111255, 0.0625]
yours = gradf(2, 3, 4)
for dim in range(3):
  ok = 'OK' if abs(yours[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {yours[dim]}")

# now estimate the gradient numerically without any calculus, using
# the approximation we used in the video.
# you should not call the function df from the last cell

# -----------
numerical_grad = [0, 0, 0] # TODO
# -----------
def f(a, b, c):
    from math import sin
    return -a**3 + sin(3*b) - 1.0/c + b**2.5 - a**0.5

# Approximate the gradient numerically
def numerical_grad_f(a, b, c):
    epsilon = 1e-7

    # Approximate df/da
    numerical_grad[0] = (f(a + epsilon, b, c) - f(a, b, c)) / epsilon

    # Approximate df/db
    numerical_grad[1] = (f(a, b + epsilon, c) - f(a, b, c)) / epsilon

    # Approximate df/dc
    numerical_grad[2] = (f(a, b, c + epsilon) - f(a, b, c)) / epsilon

    return numerical_grad

numerical_grad = numerical_grad_f(2, 3, 4)


for dim in range(3):
  ok = 'OK' if abs(numerical_grad[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad[dim]}")

# there is an alternative formula that provides a much better numerical
# approximation to the derivative of a function.
# learn about it here: https://en.wikipedia.org/wiki/Symmetric_derivative
# implement it. confirm that for the same step size h this version gives a
# better approximation.

# -----------
numerical_grad2 = [0, 0, 0] # TODO
# -----------
def f(a, b, c):
    from math import sin
    return -a**3 + sin(3*b) - 1.0/c + b**2.5 - a**0.5

# Approximate the gradient numerically
def numerical_grad_f(a, b, c):
    epsilon = 1e-7

    # Approximate df/da
    numerical_grad2[0] = (f(a + epsilon, b, c) - f(a-epsilon, b, c)) / (2*epsilon)

    # Approximate df/db
    numerical_grad2[1] = (f(a, b + epsilon, c) - f(a, b-epsilon, c)) / (2*epsilon)

    # Approximate df/dc
    numerical_grad2[2] = (f(a, b, c + epsilon) - f(a, b, c-epsilon)) / (2*epsilon)

    return numerical_grad2

numerical_grad2 = numerical_grad_f(2, 3, 4)

for dim in range(3):
  ok = 'OK' if abs(numerical_grad2[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad2[dim]}")

"""## section 2: support for softmax"""

# Value class starter code, with many functions taken out
from math import exp, log,exp

class Value:

  def __init__(self, data, _children=(), _op='', label=''):
    self.data = data
    self.grad = 0.0
    self._backward = lambda: None
    self._prev = set(_children)
    self._op = _op
    self.label = label

  def __repr__(self):
    return f"Value(data={self.data})"

  def __add__(self, other): # exactly as in the video
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data + other.data, (self, other), '+')

    def _backward():
      self.grad += 1.0 * out.grad
      other.grad += 1.0 * out.grad
    out._backward = _backward

    return out

  def __mul__(self, other): # exactly as in the video
    other = other if isinstance(other, Value) else Value(other)
    out = Value((self.data*other.data), (self, other), '*')

    def _backward():
      self.grad += (other.data) * out.grad
      other.grad += (self.data)* out.grad
    out._backward = _backward

    return out

  def __pow__(self, other): # exactly as in the video
    out = Value(self.data**other, (self, ), '^')

    def _backward():
      self.grad += (other*(self.data)**(other-1))* out.grad
    out._backward = _backward

    return out

  def __truediv__(self,other):
    return self*other**-1

  def exp(self):
      x = self.data
      out = Value(exp(x),(self,),'e^x')

      def _backward():
          self.grad += out.data*out.grad
      out._backward = _backward
      return out

  def log(self):
    x = self.data
    out = Value(log(x),(self,),'log')

    def _backward():
      self.grad += (1/x)*out.grad
    out._backward = _backward
    return out

  def __radd__(self,other):
    return self+other

  def __neg__(self):
    return self*-1
  # ------
  # re-implement all the other functions needed for the exercises below
  # your code here
  # TODO
  # ------

  def backward(self): # exactly as in video
    topo = []
    visited = set()
    def build_topo(v):
      if v not in visited:
        visited.add(v)
        for child in v._prev:
          build_topo(child)
        topo.append(v)
    build_topo(self)

    self.grad = 1.0
    for node in reversed(topo):
      node._backward()

# without referencing our code/video __too__ much, make this cell work
# you'll have to implement (in some cases re-implemented) a number of functions
# of the Value object, similar to what we've seen in the video.
# instead of the squared error loss this implements the negative log likelihood
# loss, which is very often used in classification.

# this is the softmax function
# https://en.wikipedia.org/wiki/Softmax_function
def softmax(logits):
  counts = [logit.exp() for logit in logits]
  denominator = sum(counts)

  out = [c / denominator for c in counts]
  return out

# this is the negative log likelihood loss function, pervasive in classification
logits = [Value(0.0), Value(3.0), Value(-2.0), Value(1.0)]
probs = softmax(logits)
loss = -probs[3].log() # dim 3 acts as the label for this input example
loss.backward()

ans = [0.041772570515350445, 0.8390245074625319, 0.005653302662216329, -0.8864503806400986]
for dim in range(4):
  ok = 'OK' if abs(logits[dim].grad - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits[dim].grad}")

# verify the gradient using the torch library
# torch should give you the exact same gradient
import torch

# this is the negative log likelihood loss function, pervasive in classification
logits0 = [Value(0.0), Value(3.0), Value(-2.0), Value(1.0)]
x1 = torch.tensor(0.0).double();x1.requires_grad = True
x2 = torch.tensor(3.0).double();x2.requires_grad = True
x3 = torch.tensor(-2.0).double();x3.requires_grad = True
x4 = torch.tensor(1.0).double();x4.requires_grad = True


logits = [x1,x2,x3,x4]
probs = softmax(logits)
loss = -probs[3].log() # dim 3 acts as the label for this input example
loss.backward()

for dim in range(4):
  print(logits[0].grad.item())
  ok = 'OK' if abs(logits[dim].grad - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits[dim].grad}")

